// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBaiGiang_CKC.Data;

#nullable disable

namespace WebBaiGiang_CKC.Migrations
{
    [DbContext(typeof(WebBaiGiangContext))]
    [Migration("20251116164624_AddNotificationUrl")]
    partial class AddNotificationUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HocVien_LopHoc", b =>
                {
                    b.Property<int>("MaHocVien")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("MaHocVien", "MaLopHoc");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("HOCVIEN_LOPHOC");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.Bai", b =>
                {
                    b.Property<int>("BaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaiId"), 1L, 1);

                    b.Property<int>("MaChuong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<int>("SoBai")
                        .HasColumnType("int");

                    b.Property<string>("TenBai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BaiId");

                    b.HasIndex("MaChuong");

                    b.ToTable("BAI");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.BaiLam", b =>
                {
                    b.Property<int>("BaiLamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaiLamId"), 1L, 1);

                    b.Property<float?>("Diem")
                        .HasColumnType("real");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int?>("SoCauDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDenHan")
                        .HasColumnType("datetime2");

                    b.HasKey("BaiLamId");

                    b.HasIndex("MaHocVien");

                    b.ToTable("BAILAM");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.BaiTap", b =>
                {
                    b.Property<int>("MaBaiTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiTap"), 1L, 1);

                    b.Property<int>("BaiId")
                        .HasColumnType("int");

                    b.Property<string>("FileDinhKem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("HanNop")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LateSubmission")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("RemindToGrade")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBaiTap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaBaiTap");

                    b.HasIndex("BaiId");

                    b.ToTable("BAITAP");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.BaiTapNop", b =>
                {
                    b.Property<int>("MaBaiTapNop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiTapNop"), 1L, 1);

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("FileNop")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LanNop")
                        .HasColumnType("int");

                    b.Property<int>("MaBaiTap")
                        .HasColumnType("int");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBaiTapNop");

                    b.HasIndex("MaBaiTap");

                    b.HasIndex("MaHocVien");

                    b.ToTable("BAITAPNOP");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.CauHoi", b =>
                {
                    b.Property<int>("CauHoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauHoiId"), 1L, 1);

                    b.Property<string>("DapAnA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DoKho")
                        .HasColumnType("real");

                    b.Property<int>("MaChuong")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLanLay")
                        .HasColumnType("int");

                    b.Property<int?>("SoLanTraLoiDung")
                        .HasColumnType("int");

                    b.HasKey("CauHoiId");

                    b.HasIndex("MaChuong");

                    b.ToTable("CAUHOI");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.CauHoi_BaiLam", b =>
                {
                    b.Property<int>("CauHoi_BaiLamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauHoi_BaiLamId"), 1L, 1);

                    b.Property<int>("BaiLamId")
                        .HasColumnType("int");

                    b.Property<int>("CauHoi_DeId")
                        .HasColumnType("int");

                    b.Property<string>("DapAnSVChon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CauHoi_BaiLamId");

                    b.HasIndex("BaiLamId");

                    b.HasIndex("CauHoi_DeId");

                    b.ToTable("CauHoi_BaiLam");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.CauHoi_De", b =>
                {
                    b.Property<int>("CauHoi_DeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauHoi_DeId"), 1L, 1);

                    b.Property<int>("CauHoiId")
                        .HasColumnType("int");

                    b.Property<int>("DeId")
                        .HasColumnType("int");

                    b.HasKey("CauHoi_DeId");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("DeId");

                    b.ToTable("CauHoi_De");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.ChuongNew", b =>
                {
                    b.Property<int>("MaChuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuong"), 1L, 1);

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaChuong");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("CHUONG_NEW");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.DanhSachThi", b =>
                {
                    b.Property<int>("DanhSachThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhSachThiId"), 1L, 1);

                    b.Property<int>("KyKiemTraId")
                        .HasColumnType("int");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("DanhSachThiId");

                    b.HasIndex("KyKiemTraId");

                    b.HasIndex("MaHocVien");

                    b.ToTable("DANHSACHTHI");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.De", b =>
                {
                    b.Property<int>("DeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeId"), 1L, 1);

                    b.Property<float>("DoKhoDe")
                        .HasColumnType("real");

                    b.Property<int>("KyKiemTraId")
                        .HasColumnType("int");

                    b.Property<int>("SoCauHoi")
                        .HasColumnType("int");

                    b.HasKey("DeId");

                    b.HasIndex("KyKiemTraId");

                    b.ToTable("De");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"), 1L, 1);

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHocVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"), 1L, 1);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KHOAHOC");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.KyKiemTra", b =>
                {
                    b.Property<int>("KyKiemTraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KyKiemTraId"), 1L, 1);

                    b.Property<string>("TenKyKiemTra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianLamBai")
                        .HasColumnType("int");

                    b.HasKey("KyKiemTraId");

                    b.ToTable("KyKiemTra");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHoc"), 1L, 1);

                    b.Property<string>("AnhLopHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLopHoc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("LOPHOC");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.Muc", b =>
                {
                    b.Property<int>("MucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MucId"), 1L, 1);

                    b.Property<int>("BaiId")
                        .HasColumnType("int");

                    b.Property<int>("MucSo")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.Property<string>("TenMuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MucId");

                    b.HasIndex("BaiId");

                    b.ToTable("MUCCON");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NOTIFICATION");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.TaiKhoanNew", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"), 1L, 1);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoanNews");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.TaiLieu", b =>
                {
                    b.Property<int>("MaTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiLieu"), 1L, 1);

                    b.Property<string>("FileTaiLieu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaMucCon")
                        .HasColumnType("int");

                    b.HasKey("MaTaiLieu");

                    b.HasIndex("MaMucCon");

                    b.ToTable("TAILIEU");
                });

            modelBuilder.Entity("HocVien_LopHoc", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.HocVien", "HocVien")
                        .WithMany("HocVien_LopHocs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBaiGiang_CKC.Models.LopHoc", "LopHoc")
                        .WithMany("HocVien_LopHocs")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.Bai", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.ChuongNew", "Chuong")
                        .WithMany("Bais")
                        .HasForeignKey("MaChuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuong");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.BaiLam", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.BaiTap", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.Bai", "Bai")
                        .WithMany("BaiTaps")
                        .HasForeignKey("BaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bai");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.BaiTapNop", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.BaiTap", "BaiTap")
                        .WithMany("BaiTapNops")
                        .HasForeignKey("MaBaiTap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiang_CKC.Models.HocVien", "HocVien")
                        .WithMany("BaiTapNops")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiTap");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.CauHoi", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.ChuongNew", "ChuongNew")
                        .WithMany()
                        .HasForeignKey("MaChuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongNew");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.CauHoi_BaiLam", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.BaiLam", "BaiLam")
                        .WithMany("CauHoi_BaiLam")
                        .HasForeignKey("BaiLamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiang_CKC.Models.CauHoi_De", "CauHoi_De")
                        .WithMany("CauHoi_BaiLam")
                        .HasForeignKey("CauHoi_DeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiLam");

                    b.Navigation("CauHoi_De");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.CauHoi_De", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.CauHoi", "CauHoi")
                        .WithMany("CauHoi_De")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiang_CKC.Models.De", "De")
                        .WithMany("CauHoi_DeThi")
                        .HasForeignKey("DeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("De");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.ChuongNew", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.LopHoc", "LopHoc")
                        .WithMany("Chuongs")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.DanhSachThi", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.KyKiemTra", "KyKiemTra")
                        .WithMany("DanhSachThi")
                        .HasForeignKey("KyKiemTraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiang_CKC.Models.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KyKiemTra");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.De", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.KyKiemTra", "KyKiemTra")
                        .WithMany("De")
                        .HasForeignKey("KyKiemTraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyKiemTra");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.GiangVien", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.TaiKhoanNew", "TaiKhoan")
                        .WithOne("GiangVien")
                        .HasForeignKey("WebBaiGiang_CKC.Models.GiangVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.HocVien", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.TaiKhoanNew", "TaiKhoan")
                        .WithOne("HocVien")
                        .HasForeignKey("WebBaiGiang_CKC.Models.HocVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.LopHoc", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.GiangVien", "GiangVien")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBaiGiang_CKC.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.Muc", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.Bai", "Bai")
                        .WithMany("Mucs")
                        .HasForeignKey("BaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bai");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.TaiLieu", b =>
                {
                    b.HasOne("WebBaiGiang_CKC.Models.Muc", "Muc")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaMucCon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muc");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.Bai", b =>
                {
                    b.Navigation("BaiTaps");

                    b.Navigation("Mucs");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.BaiLam", b =>
                {
                    b.Navigation("CauHoi_BaiLam");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.BaiTap", b =>
                {
                    b.Navigation("BaiTapNops");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.CauHoi", b =>
                {
                    b.Navigation("CauHoi_De");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.CauHoi_De", b =>
                {
                    b.Navigation("CauHoi_BaiLam");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.ChuongNew", b =>
                {
                    b.Navigation("Bais");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.De", b =>
                {
                    b.Navigation("CauHoi_DeThi");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.GiangVien", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.HocVien", b =>
                {
                    b.Navigation("BaiTapNops");

                    b.Navigation("HocVien_LopHocs");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.KhoaHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.KyKiemTra", b =>
                {
                    b.Navigation("DanhSachThi");

                    b.Navigation("De");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.LopHoc", b =>
                {
                    b.Navigation("Chuongs");

                    b.Navigation("HocVien_LopHocs");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.Muc", b =>
                {
                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("WebBaiGiang_CKC.Models.TaiKhoanNew", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("HocVien");
                });
#pragma warning restore 612, 618
        }
    }
}
